<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CookieJar.Host</AssemblyName>
    <RootNamespace>CookieJar.Host</RootNamespace>
    <PublishSingleFile>false</PublishSingleFile>
  </PropertyGroup>

</Project>
